POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"Produit 5",
    "description": "Produit 5",
    "price": 66
}

###
POST http://localhost:3000/products/buy
Content-Type: application/json

["642e8f97bcf129fdf85ea3e3","642e8faabcf129fdf85ea3e5"]